### ISSUE TITLE
Clarify supported operating systems

### ISSUE THREAD

**Issue by sanmai-NL** [mentaljam/standard_paths#1]
The most important issue in evaluating this crate is what operating systems it supports. Right now you mention it works on Windows and Unix. Reading https://doc.rust-lang.org/reference/attributes.html#conditional-compilation, it appears as if this includes macOS, but one can’t be too sure. Could you elaborate a bit in the README and API docs to make this 100 % clear to every potential user?

**Comment by sanmai-NL** [comment]
Extra note. The `QStandardPaths` docs themselves are clear. Your port is still early, though, compared to the current maturity of `QStandardPaths`, so that doesn’t reflect the supported OS’es yet. A potential source of confusion.

**Comment by mentaljam** [comment]
I fully agree with your comment. I have no ability to test it on macOS and don't want to publish any "blind" changes. So currently macOS is leaved unsupported until someone helps with it.

**Comment by mentaljam** [comment]
Please let me know if this issue could be closed now.

**Comment by sanmai-NL** [comment]
Yes, thanks!

macOS can be tested via [Travis CI](https://docs.travis-ci.com/user/reference/osx/). Would be wise to call for help in the README too, there are probably many Rustaceans using macOS. 🙂
